#! /usr/bin/env bash

version='2.2.52'
url="http://download.savannah.gnu.org/releases/acl/acl-${version}.src.tar.gz"
domain=core.appfs.rkeene.org
sha256='179074bb0580c06c4b4137be4c5a92a701583277967acdb5546043c7874e0d23'
require=(attr)

function prebuild() {
	echo "# Ignore: DESTDIR" >> Makefile
}

function install() {
	make install install-dev install-lib DESTDIR="${destdir}"
}

function postinstall() {
	rm -f "${destdir}/${prefix}/libexec/libacl.so"
	mv "${destdir}/${prefix}"/libexec/* "${destdir}/${prefix}/lib/"
	rm -rf "${destdir}/${prefix}/libexec"
}
