#! /usr/bin/env bash

version=4.9.2
url="http://ftp.gnu.org/gnu/gcc/gcc-${version}/gcc-${version}.tar.gz"
domain=core.appfs.rkeene.org
sha256='3e573826ec8b0d62d47821408fbc58721cd020df3e594cd492508de487a43b5e'
require=(zlib binutils:PATH linux-headers/2.6.32.63)
configure_extra=(--disable-multilib)
