#! /usr/bin/env bash

version=2.20
url="http://ftp.gnu.org/gnu/glibc/glibc-${version}.tar.xz"
domain=core.appfs.rkeene.org
sha256='f84b6d42aecc288d593c397b0a3d02260a33ee686bce0c634eb9b32798f36ba5'

function configure() {
	mkdir BUILD
	cd BUILD

	../configure --prefix="${prefix}" --sysconfdir=/etc --localstatedir=/var || return 1

	echo '# Ignore: DESTDIR' >> Makefile
}
