#! /usr/bin/env bash

version='6.0.0a'
url="http://ftp.gnu.org/gnu/gmp/gmp-6.0.0a.tar.xz"
domain=core.appfs.rkeene.org
sha256='9156d32edac6955bc53b0218f5f3763facb890b73a835d5e1b901dcf8eb8b764'

function postinstall() {
	rm -f "${destdir}/${prefix}/share/info/dir"
}
