#! /usr/bin/env bash

version='2.24'
url="http://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-${version}.tar.xz"
domain=core.appfs.rkeene.org
sha256='cee4568f78dc851d726fc93f25f4ed91cc223b1fe8259daa4a77158d174e6c65'
require=(attr)

function configure() {
	:
}

function build() {
	make prefix="${prefix}" lib='lib'
}

function install() {
	make prefix="${prefix}" lib='lib' DESTDIR="${destdir}" RAISE_SETFCAP='no' install 
}
