#! /usr/bin/env bash

version='3.17.2'
url="https://www.kernel.org/pub/linux/kernel/v3.x/linux-${version}.tar.xz"
domain=core.appfs.rkeene.org
sha256='f9221dc0878955318ab57b8bb5ea1f26cbbaa39359c91d0f6c8de74d68aea796'

function configure() {
	:
}

function build() {
	make defconfig || die
}

function install() {
	make INSTALL_HDR_PATH="${destdir}/${prefix}" headers_install || die
}
