#! /usr/bin/env bash

version='3.1.2'
url="http://ftp.gnu.org/gnu/mpfr/mpfr-${version}.tar.xz"
domain=core.appfs.rkeene.org
sha256='399d0f47ef6608cc01d29ed1b99c7faff36d9994c45f36f41ba250147100453b'
require=(gmp)
