#! /usr/bin/env bash

version=6.3
url="https://ftp.gnu.org/gnu/readline/readline-${version}.tar.gz"
domain=core.appfs.rkeene.org
sha256='56ba6071b9462f980c5a72ab0023893b65ba6debb4eeb475d7a563dc65cafd43'
